### ISSUE TITLE
Tensor size mismatch while concatenating tokenizer embedding and flowgnn_embed

### ISSUE THREAD

**Issue by sliu274** [ISU-PAAL/DeepDFA#1]
When I run `bash scripts/msr_train_combined.sh 1 MSR`, 
There is a size mismatch between the tokenizer embedding and flowgnn embedding when executing line 18 of `linevul_models.py`: `x = torch.cat((x, flowgnn_embed), dim=1)`. 

The error message is: 
```
File "~/data/data/LineVul/linevul/linevul_model.py", line 18, in forward
    x = torch.cat((x, flowgnn_embed), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 16 for tensor number 1 in the list.
```

When I change batch size from 16 to 8. The error becomes `Expected size 4 but got size 8`

The detailed error report is:

```
Traceback (most recent call last):
  File "linevul_main.py", line 668, in <module>
    main()
  File "linevul_main.py", line 641, in main
    train(args, train_dataset, model, tokenizer, eval_dataset, flowgnn_dataset)
  File "linevul_main.py", line 199, in train
    loss, logits = model(input_ids=inputs_ids, labels=labels, graphs=graphs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 185, in forward
    outputs = self.parallel_apply(replicas, inputs, module_kwargs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 200, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 110, in parallel_apply
    output.reraise()
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in _worker
    output = module(*input, **kwargs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/data/data/LineVul/linevul/linevul_model.py", line 62, in forward
    logits = self.classifier(outputs, flowgnn_embed)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "~/data/data/LineVul/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "~/data/data/LineVul/linevul/linevul_model.py", line 18, in forward
    x = torch.cat((x, flowgnn_embed), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 16 for tensor number 1 in the list.
```

**Comment by sliu274** [comment]
I figured out why this error happens. In `linevul_main.py`, when `args.n_gpu > 1`, it has parallel training while DDFA model does not do parallel training.

I have two GPUs on my server, thus the batch size for LineVul model becomes 8 while the batch size for DDFA remains 16. I resolve this issue by disabling the parallel training in `linevul_main.py`.

**Comment by bstee615** [comment]
Glad you found a solution. That sounds like it's the right explanation. Thank you for sharing it!

**Comment by bstee615** [comment]
FYI I've updated this repository with tested and working instructions for running the experiments, and fixed the bugs which were reported as of recent. Hope it helps!
